[package]
name = "pollinate"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#TODO Badges, meta data

[dependencies]
parking_lot = { version = "0.12.2", default-features = false }

[features]
std = []
